# Generated by Django 5.2.7 on 2025-10-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
