# Generated by Django 5.2.7 on 2025-10-19 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
